Repository ros2/ros2_documentation, pull requests merged in 2018-12, with the labels that each got.

#30 Update install command for OpenSplice
  Linux-Development-Setup.rst
Labels: in review

#32 Minor cleanup of intra process comm tutorial
  Intra-Process-Communication.rst
Labels: in review

#36 Set locale when installing from debian packages
  Linux-Install-Debians.rst
Labels: in review

#42 install PyQt5 on Windows for rqt
  Windows-Development-Setup.rst
  Windows-Install-Binary.rst
Labels: in review

#45 Add `lsb-release` to Setup Sources
  Linux-Install-Debians.rst
Labels: in progress

#47 Replace python script with ros2 lifecycle
  Managed-Nodes.rst
Labels: in review

#48 [Composition] Broken link
  Composition.rst
Labels: in review

#49 Link to bloom and intersphinx examples
  Inter-Sphinx-Support.rst
  Releasing-a-ROS-2-package-with-bloom.rst
  Tutorials.rst
Labels: in progress

#50 [Node Arguments] Python nodes support parameters
  Node-arguments.rst
Labels: in review

#54 [Linux Install Binary] Crystal uses opensplice 6.9
  Linux-Install-Binary.rst
Labels: in review

#52 Update name of Connext setup script
  OSX-Development-Setup.rst
Labels: in progress

#55 fix formatting in Connext security plugins page
  Install-Connext-Security-Plugins.rst
Labels: in review

#28 Add initial documentation for RQT2
  RQt-Overview-Usage.rst
  RQt-Source-Install.rst
  Tutorials.rst
Labels: in review

#24 Add section about changing RMW API to developer guide
  Developer-Guide.rst
Labels: in review

#39 Update version of OpenSplice referenced in docs.
  Linux-Development-Setup.rst
  Linux-Install-Binary.rst
  OSX-Development-Setup.rst
  Windows-Development-Setup.rst
  Windows-Install-Binary.rst
Labels: in review

#34 Updates for Crystal installation
  Linux-Install-Debians.rst
Labels: in progress

#59 Update apt repository URL.
  Linux-Development-Setup.rst
  Linux-Install-Debians.rst
Labels: in review

#57 Update Linux-Install-Binaries for Crystal.
  Linux-Install-Binary.rst
Labels: in review

#46 Ignore the python3-lark-parser key in rosdep
  Linux-Development-Setup.rst
Labels: in review

#61 link Crystal from the release page
  Releases.rst
Labels: in review

#56 RQt install by source for Windows and Mac
  RQt-Port-Plugin-Windows.rst
  RQt-Source-Install-MacOS.rst
  RQt-Source-Install-Windows10.rst
  RQt-Source-Install.rst
Labels: in review

#66 Fixes link to ros1_bridge instructions
  Linux-Development-Setup.rst
Labels: in progress

#62 update roadmap
  Roadmap.rst
Labels: in review

#69 Update Release Documentation for tf2_ros::Buffer
  Release-Crystal-Clemmys.rst
Labels: in review

#70 Use pytest, setuptools from pip on Bionic
  Linux-Development-Setup.rst
Labels: in progress

#72 Fix^3 broken link to intra process communication
  Composition.rst
Labels: in review

#73 Logging macros in crystal require ;
  Release-Crystal-Clemmys.rst
Labels: in review

#74 rcl get error string api changed
  Release-Crystal-Clemmys.rst
Labels: in review

#75 note about changes in rmw and rcl for Crystal related to init/shutdown
  Release-Crystal-Clemmys.rst
Labels: enhancement, in review

#71 Populate Crystal release page.
  Release-Crystal-Clemmys.rst
Labels: in progress

#76 fix some links on an Intel page
  Intel-ROS2-Projects.rst
Labels: in progress

#77 Don't hard code in RCL_SYSTEM_TIME in the migration example
  Release-Crystal-Clemmys.rst
Labels: in review

#51 Fix image links and formatting on Windows Install Binary page
  Windows-Install-Binary.rst
Labels: in review

#81 Updating PyQt5 build command
  RQt-Source-Install-Windows10.rst
Labels: in progress

#78 RQt: Cleanup grammer, fix broken links, fix indentation
  RQt-Overview-Usage.rst
  RQt-Source-Install.rst
Labels: in review

#83 use relative link to RQt-Overview-Usage
  Release-Crystal-Clemmys.rst
Labels: in review

#82 Added missing export of ROS_DISTRO to .bashrc to documentation
  Linux-Install-Debians.rst
Labels: in progress
