Repository ros2/ros2_documentation, pull requests merged in 2018-11, with the labels that each got.

#12 fix typo
  Tutorials.rst
Labels: in review

#17 Fix broken tutorial links
  Tutorials.rst
Labels: in progress

#14 Export interfaces documentation
  Migration-Guide.rst
Labels: in review

#19 Add gnupg2 to the required packages for apt-key
  Linux-Install-Debians.rst
Labels: in progress

#16 Update Working-with-multiple-RMW-implementations.rst
  Linux-Development-Setup.rst
  Working-with-multiple-RMW-implementations.rst
Labels: in review

#22 install lark parser
  Linux-Development-Setup.rst
  OSX-Development-Setup.rst
  OSX-Install-Binary.rst
  Windows-Development-Setup.rst
  Windows-Install-Binary.rst
Labels: in review

#21 Updates for crystal and index-v4.
  Releasing-a-ROS-2-package-with-bloom.rst
Labels: in progress

#23 rqt specific dependencies for macOS
  Set-up-a-new-macOS-CI-node.rst
Labels: in review

#15 Support Ubuntu 18.04 (Tier 1 Distro)
  Linux-Development-Setup.rst
Labels: in review

#25 connext license only necessary for version downloaded from website
  Linux-Development-Setup.rst
Labels: enhancement, in review
