Repository ros2/ros2_documentation, pull requests merged in 2019-08, with the labels that each got.

#311 add mypy and pytest-mock for Eloquent
  source/Installation/Eloquent/Fedora-Development-Setup.rst
  source/Installation/Eloquent/OSX-Development-Setup.rst
  source/Installation/Eloquent/Windows-Development-Setup.rst
Labels: in review

#314 Remove bouncy from active rosdistros.
  source/Releases.rst
Labels: in review

#315 reference Eloquent release page from the list of releases
  source/Releases.rst
Labels: in review

#318 fix install signature in ament tutorial
  source/Tutorials/Ament-CMake-Documentation.rst
Labels: bug, in review

#317 Update TSC membership
  source/Governance.rst
  source/Governance/acutronic.jpg
  source/Governance/samsung.svg
  source/Governance/ubuntu.svg
Labels: ready
