Repository ros2/ros2_documentation, pull requests merged in 2019-05, with the labels that each got.

#181 Update Python style guide links
  source/Contributing/Developer-Guide.rst
Labels: in progress

#182 Added section to reflect changes to get_node_names
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#183 Drop stubs and resolve missing references instead.
  conf.py
  source/Installation.rst
  source/Installation/Crystal.rst
  source/Installation/Fedora-Development-Setup.rst
  source/Installation/Install-Connext-Security-Plugins.rst
  source/Installation/Linux-Development-Setup.rst
  source/Installation/Linux-Install-Binary.rst
  source/Installation/Linux-Install-Debians.rst
  source/Installation/Maintaining-a-Source-Checkout.rst
  source/Installation/OSX-Development-Setup.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Development-Setup.rst
  source/Installation/Windows-Install-Binary.rst
  source/Installation/index.rst
Labels: in review

#179 Resolve references to Installation by routing them to Installation/Crystal
  conf.py
  source/Contributing/Set-up-a-new-Windows-CI-node.rst
  source/Contributing/Set-up-a-new-macOS-CI-node.rst
  source/Installation.rst
  source/Installation/Crystal.rst
  source/Tutorials/Building-ROS-2-on-Linux-with-Eclipse-Oxygen.rst
  source/Tutorials/RQt-Source-Install-Windows10.rst
  source/Tutorials/Real-Time-Programming.rst
Labels: in review

#184 add instructions to install xmllint on Windows
  source/Installation/Windows-Development-Setup.rst
Labels: enhancement, in review

#186 Update Release Notes for Dashing Features
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#188 Add changes to actions to Dashing release page
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#187 Parameter changes for dashing
  source/Releases/Release-Dashing-Diademata.rst
  source/Tutorials/Node-arguments.rst
Labels: in review

#190 Use the same title underline as other sections.
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#173 Move current install docs to distro-specific folder.
  conf.py
  source/Installation.rst
  source/Installation/Crystal.rst
  source/Installation/Crystal/Fedora-Development-Setup.rst
  source/Installation/Crystal/Install-Connext-Security-Plugins.rst
  source/Installation/Crystal/Linux-Development-Setup.rst
  source/Installation/Crystal/Linux-Install-Binary.rst
  source/Installation/Crystal/Linux-Install-Debians.rst
  source/Installation/Crystal/Maintaining-a-Source-Checkout.rst
  source/Installation/Crystal/OSX-Development-Setup.rst
  source/Installation/Crystal/OSX-Install-Binary.rst
  source/Installation/Crystal/Windows-Development-Setup.rst
  source/Installation/Crystal/Windows-Install-Binary.rst
  source/Releases/Beta2-Overview.rst
Labels: in review

#189 Describe changes to type names since Crystal
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#192 Dashing Notes for OpenCV, Numpy, and LXML
  source/Installation/Dashing/Linux-Development-Setup.rst
  source/Installation/Dashing/OSX-Install-Binary.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Install-Binary.rst
Labels: in progress

#185 add LICENSE file
  LICENSE
Labels: in review

#195 Add note about dependency walker
  source/Troubleshooting.rst
Labels: in review

#196 Switch the Windows debug documentation for Crystal to use Python 3.7.3.
  source/Installation/Crystal/Windows-Development-Setup.rst
Labels: in progress

#197 Update the dashing installation docs for newer Python.
  source/Installation/Dashing/Windows-Development-Setup.rst
Labels: in progress

#191 Add installation docs for Dashing.
  source/Installation.rst
  source/Installation/Dashing.rst
  source/Installation/Dashing/Fedora-Development-Setup.rst
  source/Installation/Dashing/Install-Connext-Security-Plugins.rst
  source/Installation/Dashing/Linux-Development-Setup.rst
  source/Installation/Dashing/Linux-Install-Binary.rst
  source/Installation/Dashing/Linux-Install-Debians.rst
  source/Installation/Dashing/Maintaining-a-Source-Checkout.rst
  source/Installation/Dashing/OSX-Development-Setup.rst
  source/Installation/Dashing/OSX-Install-Binary.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Install-Binary.rst
Labels: in review

#169 Add actions tutorial page
  .travis.yml
  source/Tutorials.rst
  source/Tutorials/Actions.rst
  source/Tutorials/Actions/Creating-an-Action.rst
  source/Tutorials/Actions/Writing-an-Action-Client-CPP.rst
  source/Tutorials/Actions/Writing-an-Action-Client-Python.rst
  source/Tutorials/Actions/Writing-an-Action-Server-CPP.rst
  source/Tutorials/Actions/Writing-an-Action-Server-Python.rst
  source/Tutorials/Actions/client_0.py
  source/Tutorials/Actions/client_1.py
  source/Tutorials/Actions/client_2.py
  source/Tutorials/Actions/client_3.py
  source/Tutorials/Actions/server_0.py
  source/Tutorials/Actions/server_1.py
  source/Tutorials/Actions/server_2.py
  source/Tutorials/Actions/server_3.py
Labels: in review

#205 add section about QoS and Option changes for create_{publisher, subscription}
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#213 add srv ns to logging command line
  source/Tutorials/Logging-and-logger-configuration.rst
Labels: in review

#214 Update Windows binary installation instructions for Dashing
  source/Installation/Dashing/Windows-Install-Binary.rst
Labels: in review

#221 Adding section for changes in parameter API for rclpy in Dashing.
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#234 Remove references to older distros.
  source/Installation/Dashing/OSX-Install-Binary.rst
Labels: in review

#236 document API change in memory strategy
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#225 Minimal corrections in windows development setup documentation
  source/Installation/Crystal/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
Labels: in review

#239 Correct transition 2 lifecycle listener output
  source/Tutorials/Managed-Nodes.rst
Labels: in review

#235 clarify documentation of options related to parameter behavior changes
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#230 Update ipc tutorial
  source/Tutorials/Intra-Process-Communication.rst
Labels: in review

#242 update parameter option names to be clearer
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#232 Add documentation about RCUTILS_COLORIZED_OUTPUT and RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED
  source/Tutorials/Logging-and-logger-configuration.rst
Labels: in review

#243 Fix link to composition tutorial in logging demo.
  source/Tutorials/Logging-and-logger-configuration.rst
Labels: in review

#254 Use correct rst syntax for inline literal.
  source/Tutorials/Managed-Nodes.rst
Labels: in review

#253 Update references to be Dashing specific.
  source/Installation/Dashing/Linux-Development-Setup.rst
  source/Installation/Dashing/Linux-Install-Binary.rst
  source/Installation/Dashing/Linux-Install-Debians.rst
  source/Installation/Dashing/OSX-Install-Binary.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
Labels: in review

#258 Add troubleshooting instructions for FastRTPS failing to be loaded on Windows
  source/Installation/Dashing/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Install-Binary.rst
Labels: in review

#237 Dashing release
  source/Releases.rst
  source/Releases/Release-Dashing-Diademata.rst
  source/Releases/dashing-small.png
Labels: in review

#259 Correct connext download instructions
  source/Installation/Dashing/OSX-Development-Setup.rst
  source/Installation/Dashing/OSX-Install-Binary.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Install-Binary.rst
Labels: in review

#194 Update Ament-Tutorial.rst
  source/Tutorials/Ament-Tutorial.rst
Labels: in review
