Repository ros2/ros2_documentation, pull requests merged in 2019-09, with the labels that each got.

#312 Install cryptography
  source/Installation/Eloquent/OSX-Development-Setup.rst
  source/Installation/Eloquent/Windows-Development-Setup.rst
Labels: in review

#327 Update OSX-Development-Setup.rst
  source/Installation/Eloquent/OSX-Development-Setup.rst
Labels: enhancement

#316 I would like to contribute tutorial for using Eclipse Cyclone DDS RMW
  source/Tutorials.rst
  source/Tutorials/Working-with-Eclipse-CycloneDDS.rst
Labels: in progress

#337 Update TSC membership
  source/Governance.rst
  source/Governance/arm.svg
  source/Governance/gvsc.png
  source/Governance/tardec.png
Labels: ready

#338 add note about Publisher/Subscription API break in rclcpp
  source/Releases/Release-Eloquent-Elusor.rst
Labels: in review
