Repository ros2/ros2_documentation, pull requests merged in 2019-04, with the labels that each got.

#159 refer to building from source for Windows users
  source/Installation/Windows-Development-Setup.rst
  source/Tutorials/Colcon-Tutorial.rst
Labels: in review

#144 Add TSC section
  source/Governance.rst
  source/Governance/TierIV.png
  source/Governance/acutronic.jpg
  source/Governance/amazon.svg
  source/Governance/apex.png
  source/Governance/arm.svg
  source/Governance/bosch_75h.jpg
  source/Governance/eprosima.svg
  source/Governance/intel.svg
  source/Governance/lge.svg
  source/Governance/microsoft.svg
  source/Governance/openrobotics-logo-stacked.png
  source/Governance/robotis.png
  source/Governance/tardec.png
  source/Governance/tri.jpg
  source/index.rst
Labels: ready

#161 Update security WG lead on Governance.rst
  source/Governance.rst
Labels: in progress

#162 ROS 2 Crystal can now use the latest tinyxml2 formula.
  source/Installation/OSX-Install-Binary.rst
Labels: in review

#163 swap TRI logo for landscape version
  source/Governance.rst
  source/Governance/tri.jpg
  source/Governance/tri_logo_landscape-web.svg
Labels: in progress, ready

#164 Fix broken links in linux binary installation
  source/Installation/Linux-Install-Debians.rst
Labels: in review

#158 Add more developer guidelines
  source/Contributing.rst
  source/Contributing/Developer-Guide.rst
Labels: in review

#170 Swap safety lead
  source/Governance.rst
Labels: in progress

#171 Add Manipulation WG, minor typo fix
  source/Governance.rst
Labels: in review

#172 Update Working-with-multiple-RMW-implementations.rst
  source/Tutorials/Working-with-multiple-RMW-implementations.rst
Labels: in review

#174 Update Intel-ROS2-Projects.rst
  source/Related-Projects/Intel-ROS2-Projects.rst
Labels: in review

#145 doc: Move explanation at the top
  source/Installation/Windows-Install-Binary.rst
Labels: in review

#175 Added git checkout step to tutorials
  source/Tutorials/Colcon-Tutorial.rst
Labels: in review

#168 Update composition tutorials for new tooling.
  source/Tutorials/Composition.rst
Labels: in progress

#176 fixup code-block
  source/Tutorials/Composition.rst
Labels: in review

#177 fixup running of composition launch file
  source/Tutorials/Composition.rst
Labels: in review

#178 Yield content for all redirects.
  conf.py
Labels: in progress
