Repository ros2/ros2_documentation, pull requests merged in 2019-06, with the labels that each got.

#266 The version of bloom needed is now 0.8.0 on all versions.
  source/Tutorials/Releasing-a-ROS-2-package-with-bloom.rst
Labels: in review

#268 Dashing is no longer an in-progress release.
  source/Installation.rst
Labels: in review

#274 update roadmap based on progress in Dashing
  source/Roadmap.rst
Labels: in review

#278 fix broken link
  source/Tutorials/Cross-compilation.rst
Labels: bug, in review

#282 Update link to charter doc
  source/Governance.rst
Labels: ready

#284 Add "Why ROS 2?" brochure (plus a few tweaks)
  source/Concepts.rst
  source/Contributing.rst
  source/Governance.rst
  source/Governance/ros2-tsc-charter.pdf
  source/Marketing.rst
  source/Marketing/ros2-brochure-a4-print.pdf
  source/Marketing/ros2-brochure-a4-web.pdf
  source/Marketing/ros2-brochure-ltr-print.pdf
  source/Marketing/ros2-brochure-ltr-web.pdf
  source/Releases.rst
  source/index.rst
Labels: ready
