Repository ros2/ros2_documentation, pull requests merged in 2019-03, with the labels that each got.

#132 Added ros2-dotnet
  source/Concepts/ROS-2-Client-Libraries.rst
Labels: in progress

#135 Update Dashing Diademata changelist after legacy launch deprecation.
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#123 Use $CHOOSE_ROS_DISTRO uniformly
  source/Installation/Linux-Install-Debians.rst
Labels: in review

#136 Migrates to python3 sphinx
  .travis.yml
  Makefile
Labels: in review

#133 Add more documentation for ament_cmake
  source/Tutorials.rst
  source/Tutorials/Ament-CMake-Documentation.rst
Labels: in review

#139 add note about the change to IDL
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#141 document changing setters to return reference
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#142 Update the known issues section in Crystal.
  source/Releases/Release-Crystal-Clemmys.rst
Labels: in review

#146 Update OSX-Install-Binary.rst
  source/Installation/OSX-Install-Binary.rst
Labels: in review

#140 Add guide on using Clang Thread Safety Analysis annotations
  source/Contributing/Quality-Guide.rst
Labels: in review

#151 Remove unsupported `emphasize-lines` directives.
  source/Contributing/Quality-Guide.rst
Labels: in review

#154 remove .0 from ROS 2
  source/Contributing/Migration-Guide.rst
  source/Installation/Linux-Development-Setup.rst
  source/Installation/OSX-Development-Setup.rst
  source/Installation/Windows-Development-Setup.rst
  source/index.rst
Labels: in review

#153 mention changed mapping of arrays / sequences of numeric types in Python
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#147 Fix link to development setup
  source/Tutorials/Cross-compilation.rst
Labels: in progress

#150 mention specific heading hierarchy
  source/Contributing/Developer-Guide.rst
Labels: enhancement, in review

#155 use released version of lark parser
  source/Installation/Linux-Development-Setup.rst
  source/Installation/OSX-Development-Setup.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Development-Setup.rst
  source/Installation/Windows-Install-Binary.rst
Labels: in review

#149 documented changed mapping of char
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#156 RTI connext packages provided only for amd64 architecture
  source/Installation/Linux-Development-Setup.rst
  source/Installation/Linux-Install-Binary.rst
Labels: in review

#157 [colcon tutorial] typo: recommened-> recommended
  source/Tutorials/Colcon-Tutorial.rst
Labels: in review
