Repository ros2/ros2_documentation, pull requests merged in 2019-10, with the labels that each got.

#348 add note about API break with get_actual_qos()
  source/Releases/Release-Eloquent-Elusor.rst
Labels: in review

#345 add notice about API break in rmw
  source/Releases/Release-Eloquent-Elusor.rst
Labels: enhancement

#375 Update deprecated syntax in composition tutorial
  source/Tutorials/Composition.rst
Labels: in review

#355 New tutorial for ROS 2 bag files
  source/Tutorials.rst
  source/Tutorials/ROS2Bag/RecordingAndPlayingBackData.rst
  source/Tutorials/ROS2Bag/playback.png
  source/Tutorials/ROS2Bag/record.png
Labels: in review

#377 Update qos tutorial after migration from arguments to ros parameters
  source/Tutorials/Quality-of-Service.rst
Labels: in review

#369 add CycloneDDS dependencies
  source/Installation/Dashing/Linux-Development-Setup.rst
  source/Installation/Dashing/OSX-Development-Setup.rst
  source/Installation/Dashing/OSX-Install-Binary.rst
  source/Installation/Dashing/Windows-Install-Binary.rst
  source/Installation/Eloquent/Linux-Development-Setup.rst
  source/Installation/Eloquent/OSX-Development-Setup.rst
  source/Installation/Eloquent/OSX-Install-Binary.rst
  source/Installation/Eloquent/Windows-Install-Binary.rst
Labels: enhancement, in review

#359 New tutorial for creating a workspace
  source/Tutorials.rst
  source/Tutorials/Colcon-Tutorial.rst
  source/Tutorials/Workspace/CreatingAWorkspace.rst
  source/Tutorials/Workspace/overlay.png
  source/Tutorials/Workspace/underlay.png
Labels: in review

#384 Update parameters tutorial
  source/Tutorials.rst
  source/Tutorials/Parameters/UnderstandingROS2Parameters.rst
Labels: in review

#383 remove completed items from roadmap
  source/Roadmap.rst
Labels: in review

#385 New branch for cleaning up staging
  source/Tutorials.rst
  source/Tutorials/Configuring-ROS2-Environment.rst
  source/Tutorials/Creating-A-ROS2-Package.rst
  source/Tutorials/Getting-Started-With-Ros2doctor.rst
  source/Tutorials/Launch-Files/Creating-Launch-Files.rst
  source/Tutorials/Launch-Files/mimic.png
  source/Tutorials/Launch-Files/mimic_graph.png
  source/Tutorials/Parameters/Understanding-ROS2-Parameters.rst
  source/Tutorials/Ros2bag/Recording-And-Playing-Back-Data.rst
  source/Tutorials/Ros2bag/playback.png
  source/Tutorials/Ros2bag/record.png
  source/Tutorials/Rqt-Console/Using-Rqt-Console.rst
  source/Tutorials/Rqt-Console/console.png
  source/Tutorials/Rqt-Console/info.png
  source/Tutorials/Rqt-Console/warn.png
  source/Tutorials/Services/Understanding-ROS2-Services.rst
  source/Tutorials/Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Turtlesim/Introducing-Turtlesim.rst
  source/Tutorials/Understanding-ROS2-Actions.rst
  source/Tutorials/Understanding-ROS2-Nodes.rst
  source/Tutorials/Workspace/Creating-A-Workspace.rst
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Cpp-Service-And-Client.rst
  source/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst
Labels: in review

#386 Complete tutorials set
  .travis.yml
  README.md
  conf.py
  requirements.txt
  source/Concepts/Overview-of-ROS-2-concepts.rst
  source/Installation.rst
  source/Tutorials.rst
  source/Tutorials/Colcon-Tutorial.rst
  source/Tutorials/Configuring-ROS2-Environment.rst
  source/Tutorials/Creating-A-ROS2-Package.rst
  source/Tutorials/Getting-Started-With-Ros2doctor.rst
  source/Tutorials/Launch-Files/Creating-Launch-Files.rst
  source/Tutorials/Launch-Files/mimic.png
  source/Tutorials/Launch-Files/mimic_graph.png
  source/Tutorials/Parameters/Understanding-ROS2-Parameters.rst
  source/Tutorials/Parameters/set.png
  source/Tutorials/Ros2bag/Recording-And-Playing-Back-Data.rst
  source/Tutorials/Ros2bag/playback.png
  source/Tutorials/Ros2bag/record.png
  source/Tutorials/Rqt-Console/Using-Rqt-Console.rst
  source/Tutorials/Rqt-Console/console.png
  source/Tutorials/Rqt-Console/info.png
  source/Tutorials/Rqt-Console/warn.png
  source/Tutorials/Services/Understanding-ROS2-Services.rst
  source/Tutorials/Services/clear.png
  source/Tutorials/Services/spawn.png
  source/Tutorials/Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Topics/debug.png
  source/Tutorials/Topics/pub_once.png
  source/Tutorials/Topics/pub_stream.png
  source/Tutorials/Topics/rqt_graph.png
  source/Tutorials/Topics/rqt_graph2.png
  source/Tutorials/Topics/rqt_graph3.png
  source/Tutorials/Topics/unhide.png
  source/Tutorials/Turtlesim/Introducing-Turtlesim.rst
  source/Tutorials/Turtlesim/new_pen.png
  source/Tutorials/Turtlesim/remap.png
  source/Tutorials/Turtlesim/rqt.png
  source/Tutorials/Turtlesim/set_pen.png
  source/Tutorials/Turtlesim/spawn.png
  source/Tutorials/Turtlesim/turtlesim.png
  source/Tutorials/Understanding-ROS2-Actions.rst
  source/Tutorials/Understanding-ROS2-Nodes.rst
  source/Tutorials/Workspace/Creating-A-Workspace.rst
  source/Tutorials/Workspace/overlay.png
  source/Tutorials/Workspace/underlay.png
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Cpp-Service-And-Client.rst
  source/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst
Labels: in review
