Repository ros2/ros2_documentation, pull requests merged in 2019-01, with the labels that each got.

#85 Add opencv-python to Windows pip-installed packages
  Windows-Install-Binary.rst
Labels: in review

#86 uniqueness of node names
  source/Roadmap.rst
Labels: in review

#29 Add new page for Cross-compilation
  source/Tutorials.rst
  source/Tutorials/Cross-compilation.rst
Labels: in progress

#89 Adds first rosindex.yml file
  rosindex.yml
Labels: in review

#90 readd IDL bullet
  source/Roadmap.rst
Labels: in review

#92 fix readme formating
  README.md
Labels: in review

#91 remove custom ROSDISTRO_INDEX_URL
  source/Tutorials/Releasing-a-ROS-2-package-with-bloom.rst
Labels: in review

#93 fix internal link
  source/Tutorials/Logging-and-logger-configuration.rst
Labels: bug, in review

#96 use latest branch of lark-parser
  source/Installation/Linux-Development-Setup.rst
  source/Installation/OSX-Development-Setup.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Development-Setup.rst
  source/Installation/Windows-Install-Binary.rst
Labels: in review

#87 Fixes some broken links
  source/Building-ROS-2-on-Linux-with-Eclipse-Oxygen.rst
  source/Installation/Windows-Install-Binary.rst
  source/Releases/Release-Crystal-Clemmys.rst
  source/Windows-Install-Binary.rst
Labels: bug, in progress

#99 Fix broken link to image_transport
  source/Features.rst
Labels: bug, in review

#100 mentioned signed-off-by requirement
  source/Contributing/Developer-Guide.rst
Labels: in review

#101 fix warning and trailing spaces
  source/Releases.rst
  source/Roadmap.rst
Labels: in review

#102 add Travis configuration
  .travis.yml
Labels: enhancement, in review

#104 Separate out the turtlebot2 installation.
  source/Installation/Linux-Install-Debians.rst
Labels: in progress

#94 create page and add notes about some API changes
  source/Releases.rst
  source/Releases/Release-Dashing-Diademata
Labels: in review

#103 run doc8 linter
  .travis.yml
  source/Concepts.rst
  source/Concepts/Overview-of-ROS-2-concepts.rst
  source/Concepts/ROS-2-Client-Libraries.rst
  source/Contributing/Developer-Guide.rst
  source/Contributing/Inter-Sphinx-Support.rst
  source/Contributing/MISRA-Compliance-Guide.rst
  source/Contributing/Migration-Guide.rst
  source/Contributing/Set-up-a-new-Linux-CI-node.rst
  source/Contributing/Set-up-a-new-macOS-CI-node.rst
  source/Installation/Linux-Install-Binary.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Install-Binary.rst
  source/Releases.rst
  source/Releases/Alpha-Overview.rst
  source/Releases/Release-Howto.rst
  source/Tutorials.rst
  source/Tutorials/Ament-Tutorial.rst
  source/Tutorials/Building-ROS-2-on-Linux-with-Eclipse-Oxygen.rst
  source/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2.rst
  source/Tutorials/Colcon-Tutorial.rst
  source/Tutorials/Intra-Process-Communication.rst
  source/Tutorials/Managed-Nodes.rst
  source/Tutorials/RQt-Overview-Usage.rst
  source/Tutorials/RQt-Source-Install.rst
  source/Tutorials/Rosbag-with-ROS1-Bridge.rst
  source/Tutorials/Rosidl-Tutorial.rst
  source/Tutorials/catment.rst
  source/Tutorials/dummy-robot-demo.rst
  source/index.rst
Labels: in review

#106 revamp Releases page
  source/Releases.rst
  source/Releases/ardent-small.png
  source/Releases/bouncy-small.png
  source/Releases/crystal-small.png
Labels: in review

#110 add information to the Dashing page, reference Dashing page from Roadmap
  source/Releases/Release-Dashing-Diademata.rst
  source/Roadmap.rst
Labels: in review

#111 Update System Requirements
  source/Installation/Linux-Development-Setup.rst
Labels: in review

#113 Improve locale Instructions
  source/Installation/Linux-Development-Setup.rst
Labels: in review
