Repository ros2/ros2_documentation, pull requests merged in 2019-02, with the labels that each got.

#115 fix ros1_bridge link
  source/Features.rst
Labels: bug, in review

#117 document change of ament_index_has_resource
  source/Releases/Release-Dashing-Diademata.rst
Labels: in review

#118 clarify two different kinds of migration
  source/Contributing/Migration-Guide.rst
Labels: in review

#119 Update cross-compilation instructions
  source/Tutorials/Cross-compilation.rst
Labels: in progress

#122 Update which releases are available for platforms
  source/Installation/Linux-Install-Debians.rst
Labels: in review

#116 Add brew tap for installing tinyxml2
  source/Installation/OSX-Install-Binary.rst
Labels: in review

#124 Fix Cross-compilation.rst header hierarchy
  source/Tutorials/Cross-compilation.rst
Labels: in review

#127 Adds installation instructions for log4cxx.
  source/Installation/OSX-Development-Setup.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Development-Setup.rst
  source/Installation/Windows-Install-Binary.rst
Labels: in review

#126 Clarify Ament vs Colcon
  source/Contributing/Migration-Guide.rst
Labels: in review

#130 Start documenting action namespace
  source/Contributing/Migration-Guide.rst
Labels: in review

#125 Update colcon tutorial
  source/Installation/Linux-Install-Binary.rst
  source/Installation/Linux-Install-Debians.rst
  source/Installation/OSX-Install-Binary.rst
  source/Installation/Windows-Install-Binary.rst
  source/Tutorials/Colcon-Tutorial.rst
Labels: in review

#131 update known issues for Crystal
  source/Releases/Release-Crystal-Clemmys.rst
Labels: in review
