Repository ros2/ros2_documentation, pull requests merged in 2020-06, with the labels that each got.

#738 Adding some Windows cmds
  source/Tutorials/Creating-Your-First-ROS2-Package.rst
  source/Tutorials/Custom-ROS2-Interfaces.rst
  source/Tutorials/Using-Parameters-In-A-Class-Python.rst
  source/Tutorials/Workspace/Creating-A-Workspace.rst
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Cpp-Service-And-Client.rst
  source/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
  source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst
Labels: enhancement

#758 Update Introducing-Turtlesim.rst
  source/Tutorials/Turtlesim/Introducing-Turtlesim.rst
Labels: bug

#763 Document API breaking change in spin_until_future_complete
  source/Releases/Release-Galactic-Geochelone.rst
Labels: in review

#754 Adding two new TSC members: PickNik and Rover Robotics
  source/Governance.rst
  source/Governance/picknik.jpg
  source/Governance/rover.png
Labels: ready

#773 add section if the rclpy C extension can't be found
  source/Troubleshooting/Installation-Troubleshooting.rst
Labels: enhancement
