Repository ros2/ros2_documentation, pull requests merged in 2020-04, with the labels that each got.

#590 [foxy] Install dependencies with apt instead of pip where possible
  source/Installation/Foxy/Linux-Development-Setup.rst
Labels: in review

#592 Add note about Connext locator kinds 5.1.0 compatibility
  source/Releases/Release-Foxy-Fitzroy.rst
Labels: in review

#606 add release note about changed signature
  source/Releases/Release-Foxy-Fitzroy.rst
Labels: enhancement

#539 Corrected push-ros-namespace references
  source/Tutorials/Launch-files-migration-guide.rst
Labels: help wanted

#576 Use new syntax for configuring log level from command line
  source/Concepts/Logging.rst
Labels: in review

#541 Remove OpenSplice install instructions from Foxy install pages
  source/Installation/Foxy/Linux-Development-Setup.rst
  source/Installation/Foxy/Linux-Install-Binary.rst
  source/Installation/Foxy/Linux-Install-Debians.rst
Labels: in review
