Repository ros2/ros2_documentation, pull requests merged in 2020-05, with the labels that each got.

#656 Fixed some commands in the tutorial to make it work in windows too
  source/Tutorials/Launch-Files/Creating-Launch-Files.rst
  source/Tutorials/Rqt-Console/Using-Rqt-Console.rst
  source/Tutorials/Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Understanding-ROS2-Actions.rst
Labels: enhancement

#658 Instructions to install Graphviz on Windows
  source/Installation/Foxy/Windows-Development-Setup.rst
  source/Installation/Foxy/Windows-Install-Binary.rst
Labels: enhancement

#665 Update tutorial/config-ros2-env to use `InstallationGuide`
  source/Tutorials/Configuring-ROS2-Environment.rst
Labels: in review

#666 updated path to local_setup.bat file
  source/Installation/Crystal/Windows-Development-Setup.rst
  source/Installation/Dashing/Windows-Development-Setup.rst
  source/Installation/Eloquent/Windows-Development-Setup.rst
  source/Installation/Foxy/Windows-Development-Setup.rst
Labels: bug

#697 Fix non-pointer type error by accessing the message object directly
  source/Tutorials/Single-Package-Define-And-Use-Interface.rst
Labels: bug
