Repository ros2/ros2_documentation, pull requests merged in 2021-01, with the labels that each got.

#1011 Sign up AWS RoboMaker for rosbag2 /clock roadmap item
  source/Roadmap.rst
Labels: backport-all

#1034 Add iRobot and Sony.
  source/Governance.rst
  source/Governance/irobot.png
  source/Governance/sony.svg
Labels: ready

#1033 Add Galactic feature note for externally configuring QoS
  source/Releases/Release-Galactic-Geochelone.rst
Labels: enhancement

#1044 Remove Sony logo pending permission for use in this context
  source/Governance.rst
  source/Governance/sony.svg
Labels: ready

#1065 Add Sony logo (now with permission)
  source/Governance.rst
  source/Governance/sony.png
Labels: ready
