Repository ros2/ros2_documentation, pull requests merged in 2021-03, with the labels that each got.

#1164 Remove galactic note in logging tutorial
  source/Tutorials/Logging-and-logger-configuration.rst
Labels: backport-foxy

#1178 Fixed indents. Update Writing-A-Simple-Cpp-Publisher-And-Subscriber.
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
Labels: backport-all

#1254 Update Microsoft and Canonical TSC reps.
  source/Governance.rst
Labels: ready
