Repository ros2/ros2_documentation, pull requests merged in 2021-11, with the labels that each got.

#2059 Add section about tab or auto-completion setup for colcon
  source/Tutorials/Colcon-Tutorial.rst
Labels: backport-foxy, backport-galactic

#1459 Add a guide for using and creating variant packages.
  source/How-To-Guides.rst
  source/How-To-Guides/Using-Variants.rst
Labels: backport-all

#2108 Fix remaining :ref: -> :doc:
  source/Tutorials/Ros2bag/Recording-A-Bag-From-Your-Own-Node-Python.rst
Labels: backport-galactic

#2118 Release humble spelling fix for OpenCV Mat
  source/Releases/Release-Humble-Hawksbill.rst
Labels: backport-all

#2127 Add Humble release note about geometry2#442
  source/Releases/Release-Humble-Hawksbill.rst
Labels: backport-all

#2140 Update docker guide from eloquent to {DISTRO}
  source/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.rst
Labels: backport-all

#2133 Add concept page on executors
  conf.py
  source/Concepts.rst
  source/Concepts/About-Executors.rst
  source/Concepts/images/executors_basic_principle.png
  source/Concepts/images/executors_basic_principle.pptx
  source/Concepts/images/executors_scheduling_semantics.png
  source/Concepts/images/executors_scheduling_semantics.pptx
Labels: backport-all

#2137 Planned contributions by Bosch for Humble release
  source/Roadmap.rst
Labels: backport-all

#2131 Remove Rover Robotics per today's TSC meeting. =(
  source/Governance.rst
  source/Governance/rover.png
Labels: backport-all

#2132 Change ADLink Representative per TSC Meeting
  source/Governance.rst
Labels: backport-all
