Repository ros2/ros2_documentation, pull requests merged in 2021-04, with the labels that each got.

#1283 Add installation instructions for RHEL
  source/Installation.rst
  source/Installation/RHEL-Development-Setup.rst
  source/Installation/RHEL-Install-Binary.rst
  source/Installation/RHEL-Install-RPMs.rst
  source/Installation/_RHEL-Set-Locale.rst
Labels: enhancement, in progress

#1312 fixup macos source install instructions while testing for galactic
  source/Installation/macOS-Development-Setup.rst
Labels: enhancement

#1318 Add info about sourcing shell start script for Windows
  source/Tutorials/Configuring-ROS2-Environment.rst
Labels: enhancement

#1333 Update the result of ros2 interface show
  source/Tutorials/Topics/Understanding-ROS2-Topics.rst
Labels: enhancement

#1335 Fix ros2 interface show in actions tutorial
  source/Tutorials/Understanding-ROS2-Actions.rst
Labels: bug

#1322 Set QT_QPA_PLATFORM_PLUGIN_PATH env variable
  source/Installation/Windows-Development-Setup.rst
  source/Installation/Windows-Install-Binary.rst
Labels: bug

#1352 [play back data tutorial] Make cmd copy-pastable
  source/Tutorials/Ros2bag/Recording-And-Playing-Back-Data.rst
Labels: enhancement

#1354 [create ws tuto] Use Native Tools cmd on Windows
  source/Tutorials/Workspace/Creating-A-Workspace.rst
Labels: enhancement

#1334 Update the output of the parameters tutorial to include parameter overrides
  source/Tutorials/Parameters/Understanding-ROS2-Parameters.rst
Labels: enhancement

#1366 Add missing dependencies for rqt_top and rqt_plot on macOS
  source/Installation/macOS-Development-Setup.rst
  source/Installation/macOS-Install-Binary.rst
Labels: enhancement

#1367 Swap Apex.AI TSC rep
  source/Governance.rst
Labels: ready

#1370 [cpp_pubsub] Improve instructions on Windows
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
Labels: enhancement

#1373 [py_pubsub] Improve instructions on Windows
  source/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
Labels: enhancement

#1376 [cpp_srvcli] Use `--merge-install` on Windows
  source/Tutorials/Writing-A-Simple-Cpp-Service-And-Client.rst
Labels: enhancement

#1377 [py_srvcli] Use --merge-install on Windows
  source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst
Labels: enhancement

#1383 Rolling has no converter package
  source/Tutorials/Ros2bag/Recording-And-Playing-Back-Data.rst
Labels: bug

#1381 [cpp parameters] Use --merge-install on Windows
  source/Tutorials/Using-Parameters-In-A-Class-CPP.rst
Labels: enhancement

#1384 Update required versions of bloom and catkin_pkg.
  source/Guides/Releasing-a-ROS-2-package-with-bloom.rst
Labels: backport-foxy

#1380 [custom interfaces] Use --merge-install on Windows
  source/Tutorials/Custom-ROS2-Interfaces.rst
Labels: enhancement

#1391 Remove args=None because it does nothing
  source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst
Labels: bug

#1387 Use underscores in setup.cfg
  source/Guides/Developing-a-ROS-2-Package.rst
  source/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
Labels: enhancement

#1417 Update ros2 param list output in 'Node Arguements' tutorial
  source/Guides/Node-arguments.rst
Labels: enhancement

#1419 Add missing items to the output of 'ros2 component types'
  source/Tutorials/Composition.rst
Labels: enhancement

#1418 Update the list of available command line tools
  source/Concepts/About-Command-Line-Tools.rst
Labels: enhancement

#1415 Improve the 'define and use interface' tutorial instructions for Windows
  source/Tutorials/Single-Package-Define-And-Use-Interface.rst
Labels: enhancement

#1414 Add information relevant on Windows in the colcon tutorial
  source/Tutorials/Colcon-Tutorial.rst
Labels: enhancement

#1423 Fix override qos policies rosbag guide
  source/Guides/Overriding-QoS-Policies-For-Recording-And-Playback.rst
Labels: enhancement

#1416 Fix 'Launch System' tutorial on Windows
  source/Tutorials/Launch-system.rst
Labels: enhancement

#1410 Add installation steps for rosdistro, ros2doctor dependency
  source/Installation/Windows-Install-Binary.rst
  source/Installation/macOS-Development-Setup.rst
  source/Installation/macOS-Install-Binary.rst
Labels: enhancement
