Repository ros2/ros2_documentation, pull requests merged in 2021-06, with the labels that each got.

#1643 Don't propose to simply close a terminal
  source/Tutorials/Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Turtlesim/Introducing-Turtlesim.rst
Labels: backport-all

#1468 Add guide for using Python, XML, and YAML in launch files
  source/Guides.rst
  source/Guides/Launch-file-different-formats.rst
  source/Tutorials/Launch-Files/Creating-Launch-Files.rst
Labels: enhancement

#1692 Pin mypy to version 0.761 to match Ubuntu Focal.
  source/Installation/RHEL-Development-Setup.rst
  source/Installation/Windows-Development-Setup.rst
  source/Installation/macOS-Development-Setup.rst
Labels: backport-foxy, backport-galactic
