Repository ros2/ros2_documentation, pull requests merged in 2022-02, with the labels that each got.

#2261 Add sitemap
  Makefile
  conf.py
  make_sitemapindex.py
  requirements.txt
Labels: enhancement

#2269 Sony completed "Wait For an Acknowledgment".
  source/Roadmap.rst
Labels: backport-all

#2074 Note launch behavior change in Foxy Patch 7
  source/Releases/Release-Foxy-Fitzroy.rst
Labels: backport-foxy, backport-galactic

#2262 Add release note for Foxy patch release 7
  source/Releases/Release-Foxy-Fitzroy.rst
Labels: backport-all

#2297 Use `const&` signature for read-only sub callbacks
  source/Tutorials/Custom-ROS2-Interfaces.rst
  source/Tutorials/FastDDS-Configuration/FastDDS-Configuration.rst
  source/Tutorials/Tf2/Writing-A-Tf2-Broadcaster-Cpp.rst
  source/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
Labels: backport-galactic

#2299 Documents minor differences between ROS1 and ROS2 bloom releases.
  source/How-To-Guides/Releasing-a-ROS-2-package-with-bloom.rst
Labels: backport-all

#2326 Update target of CMake to 3.8 for Rolling
  source/Contributing/Code-Style-Language-Versions.rst
Labels: backport-galactic

#2323 Added Gazebo, Navigation2, MoveIt, and micro-ROS to related projects
  source/Related-Projects.rst
Labels: backport-all

#2258 Add information about Raspberry Pi to How To Guides.
  source/How-To-Guides.rst
  source/How-To-Guides/Installing-on-Raspberry-Pi.rst
Labels: backport-all
