Repository ros2/ros2_documentation, pull requests merged in 2024-05, with the labels that each got.

#4340 Remove references to ignition in the install instructions.
  source/Installation/Alternatives/RHEL-Development-Setup.rst
  source/Installation/Alternatives/RHEL-Install-Binary.rst
Labels: backport-jazzy

#4344 Update rosdep install link.
  source/Installation/DDS-Implementations/Working-with-Eclipse-CycloneDDS.rst
  source/Installation/DDS-Implementations/Working-with-eProsima-Fast-DDS.rst
Labels: backport-all

#4342 Clarify Ubuntu Noble (24.04) in Installation instructions.
  source/Installation.rst
  source/Installation/Alternatives/Ubuntu-Development-Setup.rst
  source/Installation/Ubuntu-Install-Debians.rst
Labels: backport-jazzy

#4349 Switch all references to "fat archives" to "binary archives".
  source/How-To-Guides/Building-ROS-2-with-Tracing.rst
  source/How-To-Guides/Using-Python-Packages.rst
  source/Installation.rst
  source/Installation/Testing.rst
  source/The-ROS2-Project/Contributing/Developer-Guide.rst
  source/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.rst
Labels: backport-all

#4358 update writer->create_topic argument parameters.
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.rst
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-Py.rst
Labels: backport-jazzy

#4357 update TopicMetadata APIs with id parameter.
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-Py.rst
Labels: backport-jazzy

#4360 Tf2 tutorial minor fixups
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#4311 Gazebo sim tutorial update
  source/Tutorials/Advanced/Simulators/Gazebo/Gazebo.rst
Labels: backport-jazzy

#4375 Add in a troubleshooting note about running rviz2 with Wayland.
  source/How-To-Guides/Installation-Troubleshooting.rst
Labels: backport-jazzy

#4379 Make the heading of the section "ros2 interface show".
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.rst
Labels: backport-all

#4384 Remove Tf2 time tutorials for Python
  source/Concepts/Intermediate/About-Tf2.rst
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Py.rst
  source/Tutorials/Intermediate/Tf2/Learning-About-Tf2-And-Time-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Learning-About-Tf2-And-Time-Py.rst
  source/Tutorials/Intermediate/Tf2/Tf2-Main.rst
  source/Tutorials/Intermediate/Tf2/Time-Travel-With-Tf2-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#4377 Added pytest dependency required for launch_test ( Windows )
  source/Installation/_Windows-Install-Prerequisites.rst
Labels: backport-jazzy

#4389 Remove references to docs.ros2.org from the documentation.
  source/Concepts/Intermediate/About-Logging.rst
  source/How-To-Guides/Node-arguments.rst
  source/Tutorials/Advanced/FastDDS-Configuration.rst
  source/Tutorials/Intermediate/Writing-an-Action-Server-Client/Py.rst
  source/index.rst
Labels: backport-iron, backport-jazzy

#4395 FIx license snippets on package.xml and setup.py
  source/How-To-Guides/Migrating-from-ROS1/Migrating-CPP-Packages.rst
  source/How-To-Guides/Using-Variants.rst
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.rst
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-Py.rst
  source/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.rst
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-CPP.rst
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-Python.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Service-And-Client.rst
  source/Tutorials/Intermediate/Monitoring-For-Parameter-Changes-CPP.rst
  source/Tutorials/Intermediate/Monitoring-For-Parameter-Changes-Python.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-jazzy

#4373 Update dummy-robot-demo.rst with instruction to install from source
  source/Tutorials/Demos/dummy-robot-demo.rst
Labels: backport-jazzy

#4401 Update pytest development dependencies
  source/Installation/Alternatives/RHEL-Development-Setup.rst
  source/Installation/Alternatives/Ubuntu-Development-Setup.rst
  source/Installation/Alternatives/Windows-Development-Setup.rst
Labels: backport-jazzy

#4408 Fix minor typo in Testing/Python.rst
  source/Tutorials/Intermediate/Testing/Python.rst
Labels: backport-all

#4412 unnecessary package and uncrustify error for test tutorial example.
  source/Tutorials/Intermediate/Testing/Cpp.rst
Labels: backport-jazzy

#4416 Add in the jazzy logo.
  source/Releases/jazzy-small.png
Labels: backport-jazzy

#4422 Update release notes
  source/Releases/Release-Jazzy-Jalisco.rst
Labels: backport-all

#4343 Change how we install OpenSSL.
  source/Installation/_Windows-Install-Prerequisites.rst
Labels: backport-all

#4426 Update Composition.rst with installation instruction
  source/Tutorials/Intermediate/Composition.rst
Labels: backport-all

#4433 Simplify the colcon-argcomplete documentation.
  source/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.rst
Labels: backport-all

#4439 typo fix for group tabs.
  source/Tutorials/Demos/Logging-and-logger-configuration.rst
Labels: backport-iron, backport-jazzy

#4443 Added more jazzy release notes
  source/Releases/Release-Jazzy-Jalisco.rst
Labels: backport-all

#4447 Update the Jazzy complete changelog.
  source/Releases/Jazzy-Jalisco-Complete-Changelog.rst
Labels: backport-all

#4451 A few small fixes for installing RHEL binary.
  source/Installation/Alternatives/RHEL-Install-Binary.rst
Labels: backport-jazzy

#4455 add extended timer information of rcl/rclcpp for jazzy release note.
  source/Releases/Release-Jazzy-Jalisco.rst
Labels: backport-jazzy

#4434 tf2 listener cpp tutorial: minor syntax/wording improvements
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Cpp.rst
Labels: backport-all

#4463 security certificate CA name is sros2CA, but sros2testCA.
  source/Tutorials/Advanced/Security/The-Keystore.rst
Labels: backport-all

#4464 rename `demo_keys` into `demo_keystore` along with setup tutorial.
  source/Tutorials/Advanced/Security/Examine-Traffic.rst
  source/Tutorials/Advanced/Security/The-Keystore.rst
Labels: backport-all

#4476 Update Jazzy release notes with changes made in rosbag2 packages
  source/Releases/Release-Jazzy-Jalisco.rst
Labels: backport-all

#4474 Release Jazzy Jalisco
  Makefile
  conf.py
  source/Releases.rst
  source/Releases/Development.rst
  source/Releases/Release-Iron-Irwini.rst
  source/Releases/Release-Jazzy-Jalisco.rst
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#4493 latest reference target should be "latest-release".
  source/Releases/Release-Rolling-Ridley.rst
Labels: backport-all

#4500 Make EOL distro docs notice more obvious
  source/_templates/page.html
Labels: backport-all
