Repository ros2/ros2_documentation, pull requests merged in 2025-04, with the labels that each got.

#5180 Align the Connext RMW installation page with other DDS RMW installation pages
  source/How-To-Guides/Working-with-multiple-RMW-implementations.rst
  source/Installation/DDS-Implementations.rst
  source/Installation/DDS-Implementations/Install-Connext-Security-Plugins.rst
  source/Installation/DDS-Implementations/Install-Connext-University-Eval.rst
  source/Installation/DDS-Implementations/Working-with-RTI-Connext-DDS.rst
Labels: backport-all

#5216 Provide list of use-cases+examples for bash vs console code blocks
  source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
Labels: backport-all

#5232 Document deprecation of ament_target_dependencies in Kilted
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5230 Updated ros2 pub tutorial with autocomplete topic prototype feature.
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst
Labels: backport-jazzy

#5236 Update Beginnter-CLI-Tools docu
  source/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.rst
  source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst
  source/Tutorials/Beginner-CLI-Tools/Launching-Multiple-Nodes/Launching-Multiple-Nodes.rst
  source/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Parameters/Understanding-ROS2-Parameters.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Services/Understanding-ROS2-Services.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Beginner-CLI-Tools/Using-Rqt-Console/Using-Rqt-Console.rst
Labels: backport-all

#5240 Correct shebang
  plugins/ros_checkers.py
  source/Tutorials/Advanced/Discovery-Server/scripts/discovery_packets.py
  sphinx-lint-with-ros
Labels: backport-all

#5239 rosbag2 action record/replay support.
  source/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.rst
Labels: enhancement

#5253 Add $ to Ros2Doctor
  source/Tutorials/Beginner-Client-Libraries/Getting-Started-With-Ros2doctor.rst
Labels: backport-all

#5254 Add $ to Single Package Define And Use Interface
  source/Tutorials/Beginner-Client-Libraries/Single-Package-Define-And-Use-Interface.rst
Labels: backport-all

#5250 Add $ to source Creating-A-Workspace.rst
  source/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.rst
Labels: backport-all

#5251 Add $ to Colcon-Tutorial.rst
  source/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.rst
Labels: backport-all

#5255 Add $ to Using-Parameters-In-A-Class-CPP.rst
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-CPP.rst
Labels: backport-all

#5256 Add $ to Using-Parameters-In-A-Class-Python.rst
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-Python.rst
Labels: backport-all

#5258 Add $ to Writing-A-Simple-Cpp-Service-And-Client.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.rst
Labels: backport-all

#5260 Add $ to Writing-A-Simple-Py-Service-And-Client.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Service-And-Client.rst
Labels: backport-all

#5257 Add $ to Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
Labels: backport-all

#5261 Remove extra chars mistakenly added in #5236
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Services/Understanding-ROS2-Services.rst
Labels: backport-all

#5284 Mention PathJoinSubstitution improvement in Kilted release notes
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5287 Add $ to Intermediate/Tutorials
  source/Tutorials/Intermediate/Launch/Creating-Launch-Files.rst
  source/Tutorials/Intermediate/Launch/Launch-system.rst
  source/Tutorials/Intermediate/Launch/Using-Event-Handlers.rst
  source/Tutorials/Intermediate/Launch/Using-ROS2-Launch-For-Large-Projects.rst
  source/Tutorials/Intermediate/Launch/Using-Substitutions.rst
Labels: backport-all

#5286 Add $ to Creating-Your-First-ROS2-Package
  source/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.rst
Labels: backport-all

#5298 Use console code-blocks if using $
  source/Tutorials/Intermediate/Launch/Launch-system.rst
  source/Tutorials/Intermediate/Launch/Using-Substitutions.rst
Labels: backport-all

#5224 Mention preferring one Python import per line in code style guide
  source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
Labels: backport-all

#5309 Add $ to TF2 Tutorials
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Py.rst
  source/Tutorials/Intermediate/Tf2/Debugging-Tf2-Problems.rst
  source/Tutorials/Intermediate/Tf2/Introduction-To-Tf2.rst
  source/Tutorials/Intermediate/Tf2/Learning-About-Tf2-And-Time-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Time-Travel-With-Tf2-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Using-Stamped-Datatypes-With-Tf2-Ros-MessageFilter.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#5312 Add $ to Advanced Tutorials
  source/Tutorials/Advanced/Allocator-Template-Tutorial.rst
  source/Tutorials/Advanced/Ament-Lint-For-Clean-Code.rst
  source/Tutorials/Advanced/Discovery-Server/Discovery-Server.rst
  source/Tutorials/Advanced/FastDDS-Configuration.rst
  source/Tutorials/Advanced/Improved-Dynamic-Discovery.rst
  source/Tutorials/Advanced/ROS2-Tracing-Trace-and-Analyze.rst
  source/Tutorials/Advanced/Reading-From-A-Bag-File-CPP.rst
  source/Tutorials/Advanced/Reading-From-A-Bag-File-Python.rst
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.rst
  source/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-Py.rst
  source/Tutorials/Advanced/Simulators/Gazebo/Gazebo.rst
  source/Tutorials/Advanced/Simulators/Webots/Installation-MacOS.rst
  source/Tutorials/Advanced/Simulators/Webots/Installation-Ubuntu.rst
  source/Tutorials/Advanced/Simulators/Webots/Installation-Windows.rst
  source/Tutorials/Advanced/Simulators/Webots/Setting-Up-Simulation-Webots-Advanced.rst
  source/Tutorials/Advanced/Simulators/Webots/Setting-Up-Simulation-Webots-Basic.rst
  source/Tutorials/Advanced/Simulators/Webots/Simulation-Supervisor.rst
  source/Tutorials/Advanced/Topic-Statistics-Tutorial/Topic-Statistics-Tutorial.rst
Labels: backport-all

#5323 Keep information before command prompt symbol in misc tutorial
  source/Tutorials/Miscellaneous/Deploying-ROS-2-on-IBM-Cloud.rst
Labels: backport-all

#5327 Fix indentation in tf2 tutorials
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#5322 Adding $ to some How-To-Guides
  source/Concepts/Basic/About-Command-Line-Tools.rst
  source/Concepts/Intermediate/About-RQt.rst
  source/How-To-Guides/Ament-CMake-Documentation.rst
  source/How-To-Guides/Building-ROS-2-with-Tracing.rst
  source/How-To-Guides/Configure-ZeroCopy-loaned-messages.rst
  source/How-To-Guides/DDS-tuning.rst
  source/How-To-Guides/Developing-a-ROS-2-Package.rst
  source/How-To-Guides/Documenting-a-ROS-2-Package.rst
  source/How-To-Guides/Getting-Backtraces-in-ROS-2.rst
  source/How-To-Guides/Installation-Troubleshooting.rst
  source/How-To-Guides/Installing-on-Raspberry-Pi.rst
  source/How-To-Guides/Launch-file-different-formats.rst
  source/How-To-Guides/Launching-composable-nodes.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-CPP-Package-Example.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Launch-Files.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Parameters.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Python-Package-Example.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Scripts.rst
  source/How-To-Guides/Node-arguments.rst
  source/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.rst
  source/How-To-Guides/ROS-2-IDEs.rst
  source/How-To-Guides/Releasing/Subsequent-Releases.rst
  source/How-To-Guides/Releasing/_Install-Dependencies.rst
  source/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.rst
  source/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.rst
  source/How-To-Guides/Using-Custom-Rosdistro.rst
  source/How-To-Guides/Using-Python-Packages.rst
  source/How-To-Guides/Using-ros1_bridge-Jammy-upstream.rst
  source/How-To-Guides/Using-ros2-param.rst
  source/How-To-Guides/Working-with-multiple-RMW-implementations.rst
Labels: backport-all

#5334 Fix launch file name in tutorial
  source/Tutorials/Miscellaneous/Deploying-ROS-2-on-IBM-Cloud.rst
Labels: backport-all

#5336 Replace bash with console in Developing-a-ROS2-Package
  source/How-To-Guides/Developing-a-ROS-2-Package.rst
Labels: backport-all

#5319 Added some kilted release notes
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5231 Document Zenoh
  source/Installation.rst
  source/Installation/RMW-Implementations.rst
  source/Installation/RMW-Implementations/DDS-Implementations.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-Eclipse-CycloneDDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-GurumNetworks-GurumDDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-RTI-Connext-DDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-eProsima-Fast-DDS.rst
  source/Installation/RMW-Implementations/Non-DDS-Implementations.rst
  source/Installation/RMW-Implementations/Non-DDS-Implementations/Working-with-Zenoh.rst
Labels: backport-all

#5343 fix linking WARNING: unknown document.
  Makefile
  source/Concepts/Intermediate/About-Different-Middleware-Vendors.rst
  source/How-To-Guides/Working-with-multiple-RMW-implementations.rst
  source/Tutorials/Advanced/Security/Introducing-ros2-security.rst
Labels: backport-all

#5347 Update the Rosbag2 section in the Kilted release notes
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5363 Fix formatting for Rosbag2 entries in Kilted release notes
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5346 add new features for Kilted Kaiju.
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5368 Update Static Type Checking Changelog for Kilted `rclpy`
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5357 Add $ to Related-Projects, Releases and Contributing.
  source/Related-Projects/Visualizing-ROS-2-Data-With-Foxglove.rst
  source/Releases/Release-Eloquent-Elusor.rst
  source/Releases/Release-Galactic-Geochelone.rst
  source/Releases/Release-Humble-Hawksbill.rst
  source/Releases/Release-Jazzy-Jalisco.rst
  source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
  source/The-ROS2-Project/Contributing/Developer-Guide.rst
Labels: backport-all

#5355 Add $ DDS-Implementations
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-Eclipse-CycloneDDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-GurumNetworks-GurumDDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-RTI-Connext-DDS.rst
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-eProsima-Fast-DDS.rst
Labels: backport-all

#5356 Add $ to Installation
  source/Installation/Maintaining-a-Source-Checkout.rst
  source/Installation/RHEL-Install-RPMs.rst
  source/Installation/Testing.rst
  source/Installation/Ubuntu-Install-Debs.rst
  source/Installation/Windows-Install-Binary.rst
  source/Installation/_Apt-Repositories.rst
  source/Installation/_Apt-Upgrade-Admonition.rst
  source/Installation/_Dnf-Update-Admonition.rst
  source/Installation/_RHEL-Set-Locale.rst
  source/Installation/_Ubuntu-Set-Locale.rst
Labels: backport-all

#5351 Add $ to Intermediate and Miscellaneous
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Using-Stamped-Datatypes-With-Tf2-Ros-MessageFilter.rst
  source/Tutorials/Intermediate/URDF/Using-Xacro-to-Clean-Up-a-URDF-File.rst
  source/Tutorials/Intermediate/Writing-an-Action-Server-Client/Py.rst
  source/Tutorials/Miscellaneous/Building-Realtime-rt_preempt-kernel-for-ROS-2.rst
Labels: backport-all

#5354 Add $ to Installation/Alternatives
  source/Installation/Alternatives/RHEL-Development-Setup.rst
  source/Installation/Alternatives/RHEL-Install-Binary.rst
  source/Installation/Alternatives/Ubuntu-Development-Setup.rst
  source/Installation/Alternatives/Ubuntu-Install-Binary.rst
  source/Installation/Alternatives/Windows-Development-Setup.rst
  source/Installation/Alternatives/macOS-Development-Setup.rst
Labels: backport-all

#5353 Add $ to How-To-Guides
  source/How-To-Guides/Ament-CMake-Documentation.rst
  source/How-To-Guides/Building-a-Custom-Deb-Package.rst
  source/How-To-Guides/Core-maintainer-guide.rst
  source/How-To-Guides/DDS-tuning.rst
  source/How-To-Guides/Getting-Backtraces-in-ROS-2.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-CPP-Package-Example.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Python-Package-Example.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Scripts.rst
  source/How-To-Guides/ROS-2-IDEs.rst
  source/How-To-Guides/Releasing/First-Time-Release.rst
  source/How-To-Guides/Releasing/Subsequent-Releases.rst
  source/How-To-Guides/Releasing/_Bump-Package-Version.rst
  source/How-To-Guides/Releasing/_Install-Dependencies.rst
  source/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.rst
  source/How-To-Guides/Working-with-multiple-RMW-implementations.rst
Labels: backport-all

#5359 Add $ to Beginner-CLI-Tools and Beginner-Client Libraires
  source/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.rst
  source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst
  source/Tutorials/Beginner-CLI-Tools/Using-Rqt-Console/Using-Rqt-Console.rst
  source/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.rst
  source/Tutorials/Beginner-Client-Libraries/Custom-ROS2-Interfaces.rst
  source/Tutorials/Beginner-Client-Libraries/Pluginlib.rst
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-CPP.rst
Labels: backport-all

#5352 Add $ to Demos
  source/Tutorials/Demos/Action-Introspection.rst
  source/Tutorials/Demos/Content-Filtering-Subscription.rst
  source/Tutorials/Demos/Intra-Process-Communication.rst
  source/Tutorials/Demos/Logging-and-logger-configuration.rst
  source/Tutorials/Demos/Quality-of-Service.rst
  source/Tutorials/Demos/Real-Time-Programming.rst
  source/Tutorials/Demos/Rosbag-with-ROS1-Bridge.rst
  source/Tutorials/Demos/Service-Introspection.rst
  source/Tutorials/Demos/dummy-robot-demo.rst
Labels: backport-all

#5393 Fix text misalignment in tab
  source/Tutorials/Demos/Quality-of-Service.rst
Labels: backport-all

#5399 Speficy language for some code-blocks and use ini where appropriate
  source/How-To-Guides/Developing-a-ROS-2-Package.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-CPP-Package-Example.rst
  source/How-To-Guides/Migrating-from-ROS1/Migrating-Python-Package-Example.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.rst
Labels: backport-all

#5400 Move comment to the right code line in code-block
  source/How-To-Guides/Using-Python-Packages.rst
Labels: backport-all

#5398 Split 'rosdep install' command output to separate codeblock again
  source/How-To-Guides/Installation-Troubleshooting.rst
  source/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.rst
Labels: backport-all

#5417 Fix Connext RMW installation documentation issues
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-RTI-Connext-DDS.rst
Labels: backport-all

#5409 Update Ament-CMake-Documentation.rst
  source/How-To-Guides/Ament-CMake-Documentation.rst
Labels: backport-all

#5431 Complete changelog for the kilted release
  source/Releases/Kilted-Kaiju-Complete-Changelog.rst
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5438 Add installation link for Kilted
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all
