Repository ros2/ros2_documentation, pull requests merged in 2025-05, with the labels that each got.

#5453 Add prerequisites for doing the CLI test
  source/Tutorials/Intermediate/Testing/CLI.rst
Labels: backport-all

#5465 Fix small typo in Zenoh documentation
  source/Installation/RMW-Implementations/Non-DDS-Implementations/Working-with-Zenoh.rst
Labels: backport-all

#5426 Subordinate nodes note for Kilted Kaiju.
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5482 Update fastrtps to fastdds
  source/Installation/Alternatives/RHEL-Install-Binary.rst
  source/Installation/Alternatives/Ubuntu-Install-Binary.rst
  source/Tutorials/Advanced/Security/Introducing-ros2-security.rst
Labels: backport-kilted

#5484 Update Reading-From-A-Bag-File-CPP.rst to fix build
  source/Tutorials/Advanced/Reading-From-A-Bag-File-CPP.rst
Labels: backport-kilted

#5480 Set correct code-block language in beginner CLI tutorials
  source/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-CPP.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.rst
Labels: backport-all

#5481 Fix CMake target name in simple C++ pub/sub tutorial
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.rst
Labels: backport-kilted

#5486 Fix CMake target name in simple C++ service/client tutorial and code-block
  source/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.rst
Labels: backport-kilted

#5510 Add XML & YAML example static tf publisher launch files
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/launch/static_transform_publisher_launch.xml
  source/Tutorials/Intermediate/Tf2/launch/static_transform_publisher_launch.yaml
Labels: backport-all

#5505 Update branch for links in tf2 tutorials
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Adding-A-Frame-Py.rst
  source/Tutorials/Intermediate/Tf2/Using-Stamped-Datatypes-With-Tf2-Ros-MessageFilter.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#5528 Removed argument requesting "if" block for custom msg and srv testing
  source/Tutorials/Beginner-Client-Libraries/Custom-ROS2-Interfaces.rst
Labels: backport-kilted

#5537 Fix incorrect sourcing command for Linux in Creating-an-Action tutorial
  source/Tutorials/Intermediate/Creating-an-Action.rst
Labels: backport-all

#5488 Review "Configure service introspection" for Kilted
  source/Tutorials/Demos/Service-Introspection.rst
Labels: backport-jazzy, backport-kilted

#5549 Switch to gz ionic links in Gazebo tutorial
  source/Releases/Release-Kilted-Kaiju.rst
  source/Tutorials/Advanced/Simulators/Gazebo/Gazebo.rst
Labels: backport-kilted

#5548 link action instrospection docs for Kilted Release Note.
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5564 Improve wording and examples of Writing A Tf2 Static Broadcaster
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.rst
  source/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.rst
Labels: backport-all

#5546 instruction to add the launch file in setup.py
  source/Tutorials/Intermediate/Tf2/Using-Stamped-Datatypes-With-Tf2-Ros-MessageFilter.rst
Labels: backport-all

#5591 Document that removing the scope keyworld to target_link_libraries might be necessary
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-kilted

#5600 fix up Real-Time-Programing page.
  source/Tutorials/Demos/Real-Time-Programming.rst
Labels: backport-all

#5615 update instruction for pluginlib example
  source/Tutorials/Beginner-Client-Libraries/Pluginlib.rst
Labels: backport-all

#5620 Update Windows-Development-Setup.rst with note about very long build times
  source/Installation/Alternatives/Windows-Development-Setup.rst
Labels: backport-all

#5543 Explain event callbacks in "Monitoring for parameter changes"
  source/Tutorials/Intermediate/Monitoring-For-Parameter-Changes-CPP.rst
  source/Tutorials/Intermediate/Monitoring-For-Parameter-Changes-Python.rst
Labels: backport-all

#5523 Increase page max width to show more content when possible
  conf.py
  source/_static/custom.css
Labels: backport-all

#5640 Document that cross-distro communications are not guaranteed
  source/Concepts/Intermediate/About-Different-Middleware-Vendors.rst
  source/Releases.rst
Labels: backport-all

#4235 Add draft of velocity transform specification
  source/Concepts/Intermediate/About-Tf2.rst
Labels: backport-all

#5652 Move command output into code-block in ros2_tracing tutorial
  source/Tutorials/Advanced/ROS2-Tracing-Trace-and-Analyze.rst
Labels: backport-jazzy, backport-kilted

#4977 Added zenoh security documention
  source/Tutorials/Advanced/Security/Introducing-ros2-security.rst
Labels: backport-kilted

#5668 Fix green rows in distributions table
  source/Releases.rst
Labels: backport-all

#5677 Fix incorrect new feature description in Kilted
  source/Releases/Release-Kilted-Kaiju.rst
Labels: backport-all

#5678 Indicate correct branches to checkout to build CycloneDDS from source
  source/Installation/RMW-Implementations/DDS-Implementations/Working-with-Eclipse-CycloneDDS.rst
Labels: backport-all

#5690 update curl command to handle redirects
  source/Installation/_Apt-Repositories.rst
Labels: backport-all
